ProjetoFinal/Models/Requisicao.cs
using Microsoft.AspNetCore.Authentication;
using System.ComponentModel.DataAnnotations;

namespace ProjetoFinal.Models
{
    public class Requisicao
    {

        public int Id { get; set; }

        [Required(ErrorMessage = "Selecione o produto")]
        public Produto Produto { get; set; }

        [Required(ErrorMessage = "Digite a quantidade de produtos")]
        public int Quantidade { get; set; }
    }
}

ProjetoFinal/Controllers/ProdutoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjetoFinal.Models;
using ProjetoFinal.Repositorio;

namespace ProjetoFinal.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly IProdutoRepositorio _produtoRepositorio;
       
        public ProdutoController(IProdutoRepositorio produtoRepositorio)
        {
            _produtoRepositorio = produtoRepositorio;
        }

        public IActionResult Index()
        {
            List<Produto> produtos = _produtoRepositorio.BuscarTodos();
            return View(produtos);
        }

        [Authorize]
        public IActionResult Criar()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Criar(Produto produto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _produtoRepositorio.Adicionar(produto);
                    TempData["MensagemSucesso"] = "Produto cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }

                return View(produto);
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ocorreu um erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [Authorize]
        public IActionResult Editar(int id)
        {
            Produto produto = _produtoRepositorio.ListarPorId(id);
            return View(produto);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Alterar(Produto produto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _produtoRepositorio.Atualizar(produto);
                    TempData["MensagemSucesso"] = "Produto alterado com sucesso!";
                    return RedirectToAction("Index");

                }
                return View("Editar", produto);
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Não conseguimos alterar o produto! Detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [Authorize]
        public IActionResult ApagarConfirmacao(int id)
        {
            Produto produto = _produtoRepositorio.ListarPorId(id);
            return View(produto);
        }

        [Authorize]
        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagado = _produtoRepositorio.Apagar(id);

                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Produto apagado com sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = "Não foi possível apagar o produto! Tente novamante!";
                }
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não foi possível apagar o produto! Detalhe do erro: {erro.Message}";

                return RedirectToAction("Index");
            }
        }
    }
}

ProjetoFinal/Controllers/RequisicaoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjetoFinal.Models;
using ProjetoFinal.Repositorio;

namespace ProjetoFinal.Controllers
{
    public class RequisicaoController : Controller
    {
        private readonly IRequisicaoRepositorio _requisicaoRepositorio;
        private readonly IProdutoRepositorio _produtoRepositorio;

        public RequisicaoController(IRequisicaoRepositorio requisicaoRepositorio, IProdutoRepositorio produtoRepositorio)
        {
            _requisicaoRepositorio = requisicaoRepositorio;
            _produtoRepositorio = produtoRepositorio;
        }

        public IActionResult Index()
        {
            List<Requisicao> requisicoes = _requisicaoRepositorio.BuscarTodos();
            return View(requisicoes);
        }

        [Authorize]
        public IActionResult Criar()
        {
            CarregarProdutos();

            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Criar(Requisicao requisicao)
        {
            try
            {
                Produto produto = _produtoRepositorio.ListarPorId(requisicao.Produto.Id);

                //Verifica se o estoque do produto é maior ou igual à quantidade de requisição
                if (produto.Quantidade >= requisicao.Quantidade)
                {
                    requisicao.Produto= produto;
                    _requisicaoRepositorio.Adicionar(requisicao);
                    produto.Quantidade -= requisicao.Quantidade;

                    _produtoRepositorio.Atualizar(produto);

                    TempData["MensagemSucesso"] = "Requisição cadastrada com sucesso!";
                    return RedirectToAction("Index");
                }
                else
                {
                    CarregarProdutos();

                    TempData["MensagemErro"] = "A quantidade da requisição excede a quantidade no estoque.";
                    return View(requisicao);
                }
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ocorreu um erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        /*[Authorize]
        public IActionResult Editar(int id)
        {
            Requisicao requisicao = _requisicaoRepositorio.ListarPorId(id);
            return View(requisicao);
        }*/

        /*[Authorize]
        [HttpPost]
        public IActionResult Alterar(Requisicao requisicao)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _requisicaoRepositorio.Atualizar(requisicao);
                    TempData["MensagemSucesso"] = "Requisição alterada com sucesso!";
                    return RedirectToAction("Index");

                }
                return View("Editar", requisicao);
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Não conseguimos alterar a requisição! Detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }*/

        [Authorize]
        public IActionResult ApagarConfirmacao(int id)
        {
            Requisicao requisicao = _requisicaoRepositorio.ListarPorId(id);
            return View(requisicao);
        }

        [Authorize]
        public IActionResult Apagar(int id)
        {
            try
            {
                //Retorna a quantidade de items para o estoque
                Requisicao requisicao = _requisicaoRepositorio.ListarPorId(id);
                Produto produto = requisicao.Produto;
                produto.Quantidade += requisicao.Quantidade;

                _produtoRepositorio.Atualizar(produto);

                bool apagado = _requisicaoRepositorio.Apagar(id);

                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Requisição apagada com sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = "Não foi possível apagar a requisição! Tente novamante!";
                }
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não foi possível apagar a requisição! Detalhe do erro: {erro.Message}";

                return RedirectToAction("Index");
            }
        }

        private void CarregarProdutos()
        {
            ViewBag.Produtos = _produtoRepositorio.BuscarTodos().ToList();
        }
    }
}

ProjetoFinal/Views/Requisicao/ApagarConfirmacao.cshtml
@model Requisicao
@{
    ViewData["Title"] = "Confirmação de Exclusão de Requisicao";
}

<div class="text-center">
    <h3>Deseja apagar a requisição de @Model.Quantidade items do produto "@Model.Produto.Nome" ?</h3>
</div>

<div class="d-grid gap-2">
    <a class="btn btn-primary" asp-controller="Requisicao" asp-action="Index" role="button">Cancelar exclusão</a>
    <a class="btn btn-danger" asp-action="Apagar" asp-controller="Requisicao" asp-route-id="@Model.Id" role="button">Confirmar exclusão</a>
</div>

ProjetoFinal/Views/Requisicao/Criar.cshtml
@model Requisicao

@{
    ViewData["Title"] = "Cadastrar Requisição";
}

<div class="text-center">
    <h1 class="display-4">Cadastrar Requisição</h1>
</div>

@if (TempData["MensagemSucesso"] != null)
{    
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-success btn-sm close-alert" aria-label="Close">X</button>
        @TempData["MensagemSucesso"]
    </div>    
}

@if (TempData["MensagemErro"] != null)
{ 
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
        @TempData["MensagemErro"]
    </div>
}

<form asp-controller="Requisicao" asp-action="Criar" method="post">
    <div class="mb-3">
        <label for="Produto.Id">Produto</label>        
        <select asp-for="Produto.Id" class="form-control">            
            @foreach (Produto produto in ViewBag.Produtos)
            {
                <option value="@produto.Id">@produto.Nome</option>
            }
        </select>
        @Html.ValidationMessageFor(x =>x.Produto)
    </div>

    <div class="mb-3">
        <label for="quantidade">Quantidade</label>
        <input type="number" asp-for="Quantidade" class="form-control" min="0" placeholder="Digite um número igual ou maior que zero" />
        @Html.ValidationMessageFor(x =>x.Quantidade)
    </div>

    <div class="d-grid gap-2">
        <button type="submit" class="btn btn-primary">
            Cadastrar Requisição
        </button>
        <a class="btn btn-secondary" asp-controller="Requisicao" asp-action="Index" role="button">Voltar</a>
    </div>
</form>

ProjetoFinal/Views/Requisicao/Editar.cshtml
@model Produto
@{
    ViewData["Title"] = "Editar Produto";
}
<div class="text-center">
    <h1 class="display-4">Editar Produto</h1>

</div>

<form asp-controller="Produto" asp-action="Alterar" method="post">
    <!-- nao deixar visivel o id-->
    <input type="hidden" asp-for="Id" />

    <div class="mb-3">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do produto">
        @Html.ValidationMessageFor(x =>x.Nome)
    </div>

    <div class="mb-3">
        <label for="quantidade">Quantidade</label>
        <input type="number" asp-for="Quantidade" class="form-control" min="0" placeholder="Digite um número igual ou maior que zero" />
        @Html.ValidationMessageFor(x =>x.Quantidade)
    </div>

    <div class="d-grid gap-2">
        <button type="submit" class="btn btn-primary ">Alterar Produto</button>
        <a class="btn btn-secondary" asp-controller="Produto" asp-action="Index" role="button">Voltar</a>
    </div>
</form>

ProjetoFinal/Views/Requisicao/Index.cshtml
@model List<Requisicao>

@{
    ViewData["Title"] = "Listagem de Requisições";
}

<h1>Listagem de Requisições</h1>


@if (TempData["MensagemSucesso"] != null)
{    
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-success btn-sm close-alert" aria-label="Close">X</button>
        @TempData["MensagemSucesso"]
    </div>    
}

@if (TempData["MensagemErro"] != null)
{ 
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
        @TempData["MensagemErro"]
    </div>
}

<div class="d-grid gap-2 d-md-flex justify-content-md-start">
    @if (User.Identity.IsAuthenticated)
    {
        <a class="btn btn-primary" asp-controller="Requisicao" asp-action="Criar" role="button">Adicionar nova requisição</a>
    }
</div>

<table class="table" id="table-requisicoes">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Produto</th>
            <th scope="col">Quantidade</th>            
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>       
        @if (Model != null && Model.Any())
        {
           foreach (Requisicao requisicao in Model)
            {
                <tr>
                    <th scope="row">@requisicao.Id</th>
                    <td>@requisicao.Produto.Nome</td>
                    <td>@requisicao.Quantidade</td>
                    <td>
                        <div class="btn-group" role="button">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <!--<a role="button" class="btn btn-primary" asp-controller="Requisicao" asp-route-id="@requisicao.Id" asp-action="Editar">Editar</a>-->
                                <a role="button" class="btn btn-danger" asp-controller="Requisicao" asp-route-id="@requisicao.Id" asp-action="ApagarConfirmacao">Apagar</a>
                            }
                        </div>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>